[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# -- App Libs
lib-utils = { path = "../../libs/lib-utils" }
lib-rpc = { path = "../../libs/lib-rpc" }
lib-auth = { path = "../../libs/lib-auth" }
lib-core = { path = "../../libs/lib-core" }
# -- Async
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
# -- Json
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
# -- Web
axum = { version = "0.6", features = ["macros"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["fs"] }
tower-cookies = "0.9"
# -- Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# -- Others
uuid = { version = "1", features = ["v4", "fast-rng"] }
strum_macros = "0.25"
derive_more = { version = "1.0.0-beta", features = ["from"] }
ts-rs = "8.1"


[dev-dependencies]
anyhow = "1"
httpc-test = "0.1"
serial_test = "2"
hyper = "0.14.27"
mime = "0.3"
