[env]

# 这个环境变量用于服务 tracing，用于记录 debug 模式下日志仅输出我写进代码中的 info debug error 等日志上报内容
RUST_LOG = "rust_service_app=debug"

SERVICE_DB_URL = "postgres://postgres:321chenjixink@localhost:5432/app_db"

# web 项目的静态路径
SERVICE_WEB_FOLDER = "../frontend/dist/"
SERVICE_WEB_FILE = "../frontend/dist/index.html"
